#services:
#  mysql:
#    image: 'mysql:latest'
#    environment:
#      - 'MYSQL_DATABASE=mydatabase'
#      - 'MYSQL_PASSWORD=secret'
#      - 'MYSQL_ROOT_PASSWORD=secret'
#      - 'MYSQL_USER=root'
#    ports:
#      - '3306'
